services:
   service-pg:
      image: bitnami/postgresql
      ports:
         - '5433:5432'
      environment:
         - POSTGRES_USER=vrossi
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=futanalitcs
